version: "3.3"
services:
  php-fpm:
    build:
      context: ./docker/php-fpm
      args:
        PHP_VERSION: 7.3
    env_file: .env
    user: "$_UID:$_GID"
    depends_on:
      - postgres
      - memcached
    links:
      - postgres
    volumes:
      - "./:/application"
      - "./docker/php-fpm/etc/php.ini:/usr/local/etc/php/php.ini"
    environment:
      - "PHP_IDE_CONFIG=serverName=Docker"
    working_dir: "/application"

  nginx:
    image: "nginx:1.19.2-alpine"
    env_file: .env
    ports:
      - "8080:80"
    volumes:
      - "./:/application"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - "php-fpm"

  postgres:
    image: "postgres:12-alpine"
    env_file: .env
    environment:
      - "POSTGRES_USER=$DB_USERNAME"
      - "POSTGRES_PASSWORD=$DB_PASSWORD"
      - "POSTGRES_DB=$DB_DATABASE"
    ports:
      - "5432:5432"
    volumes:
      - ./storage/postgres-data:/var/lib/postgresql/data

  migrations_and_seeders:
    build:
      context: docker/migrations_and_seeders
      args:
        PHP_VERSION: 7.3
    env_file: .env
    user: "$_UID:$_GID"
    working_dir: "/application"
    depends_on:
      - postgres
    environment:
      - "WAIT_HOSTS=postgres:$DB_PORT"
      - "CACHE_DRIVER=file"
    volumes:
      - "./:/application"

  composer:
    build:
      context: docker/composer
    env_file: .env
    user: "$_UID:$_GID"
    network_mode: "host"
    working_dir: "/application"
    depends_on:
      - postgres
    environment:
      - "COMPOSER_HOME=$COMPOSER_HOME"
      - "COMPOSER_CACHE_DIR=$COMPOSER_CACHE_DIR"
      - "CACHE_DRIVER=file"
    volumes:
      - "$COMPOSER_HOME:$COMPOSER_HOME"
      - "$COMPOSER_CACHE_DIR:$COMPOSER_CACHE_DIR"
      - "./:/application"
    command: "composer install"

  memcached:
    image: "memcached:1.6.9-alpine"
    ports:
      - 11211:11211